### PR TITLE
astro-font

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
Before: Notice the font loads shift the `Team DX @ Astro`

https://github.com/ElianCodes/ElianCodes-frontend/assets/46300090/e21766c2-9e35-4551-8c19-f466dcf6f280

**Comment by rishi-raj-jain** [comment]
After: Notice the font loads does **not** shift the Team DX @ Astro

https://github.com/ElianCodes/ElianCodes-frontend/assets/46300090/c142ef61-f4e5-4c28-aad7-9bef1a860526

**Comment by rishi-raj-jain** [comment]
After: Notice the font loads does not shift the `Team DX @ Astro`

https://github.com/ElianCodes/ElianCodes-frontend/assets/46300090/c98081e3-131d-4c81-b9c7-4a73725b091f

**Comment by ElianCodes** [comment]
Big thanks Rishi! 💜

**Comment by rishi-raj-jain** [comment]
> Big thanks Rishi! 💜

Thank you, Elian! 💜

**Pull request merged**
